## Scalars

Scalars are single numbers and are an example of a 0th-order tensor. The notation x ∈ ℝ states that x is a scalar belonging to a set of real-values numbers, ℝ.
There are different sets of numbers of interest in deep learning. ℕ represents the set of positive integers (1,2,3,…). ℤ designates the integers, which combine positive, negative and zero values. ℚ represents the set of rational numbers that may be expressed as a fraction of two integers.

In [1]:
# In-Built Scalars
a = 5
b = 7.5
print(type(a))
print(type(b))
print(a + b)
print(a - b)
print(a * b)
print(a / b)

<class 'int'>
<class 'float'>
12.5
-2.5
37.5
0.6666666666666666


The following code snippet checks if the given variable is scalar or not.

In [2]:
import numpy as np

# Is Scalar Function
def isscalar(num):
    if isinstance(num, generic):
        return True
    else:
        return False

print(np.isscalar(3.1))
print(np.isscalar([3.1]))
print(np.isscalar(False))

True
False
True


## Vectors

Vectors are ordered arrays of single numbers and are an example of 1st-order tensor. Vectors are fragments of objects known as vector spaces. A vector space can be considered of as the entire collection of all possible vectors of a particular length (or dimension). The three-dimensional real-valued vector space, denoted by ℝ^3 is often used to represent our real-world notion of three-dimensional space mathematically.<br>
To identify the necessary component of a vector explicitly, the ith scalar element of a vector is written as x[i].

In [3]:
import numpy as np

# Declaring Vectors

x = [1, 2, 3]
y = [4, 5, 6]

print(type(x))

# This does'nt give the vector addition.
print(x + y)

# Vector addition using Numpy

z = np.add(x, y)
print(z)
print(type(z))

# Vector Cross Product
mul = np.cross(x, y)
print(mul)

<class 'list'>
[1, 2, 3, 4, 5, 6]
[5 7 9]
<class 'numpy.ndarray'>
[-3  6 -3]


## Matrices

Matrices are rectangular arrays consisting of numbers and are an example of 2nd-order tensors. If m and n are positive integers, that is m, n ∈ ℕ then the m×n matrix contains m*n numbers, with m rows and n columns.

In Python, We use numpy library which helps us in creating ndimensional arrays. Which are basically matrices, we use matrix method and pass in the lists and thereby defining a matrix.

In [4]:
import numpy as np

In [5]:
x = np.matrix([[1,2],[2,3]])

In [7]:
x

matrix([[1, 2],
        [2, 3]])

In [8]:
a = x.mean(0)
a

matrix([[1.5, 2.5]])

In [10]:
b = x.mean(1)
b

matrix([[1.5],
        [2.5]])

In [11]:
c = a-b
c

matrix([[ 0.,  1.],
        [-1.,  0.]])

## Matrix Addition

Matrices can be added to scalars, vectors and other matrices. Each of these operations has a precise definition. These techniques are used frequently in machine learning and deep learning so it is worth familiarising yourself with them.

In [12]:
# Matrix Addition

import numpy as np

x = np.matrix([[1, 2], [4, 3]])

sum = x.sum()
print(sum)

10


## Matrix-Matrix Addition

C = A + B (Shape of A and B should be equal)<br>
The methods shape return the shape of the matrix, and add takes in two arguments and returns the sum of those matrices. If the shape of the matrices is not same it throws an error saying, addition not possible.


In [13]:
# Matrix-Matrix Addition

import numpy as np

x = np.matrix([[1, 2], [4, 3]])
y = np.matrix([[3, 4], [3, 10]])

print(x.shape)
# (2, 2)
print(y.shape)
# (2, 2)

m_sum = np.add(x, y)
print(m_sum)
print(m_sum.shape)

(2, 2)
(2, 2)
[[ 4  6]
 [ 7 13]]
(2, 2)


## Matrix-Scalar Addition 

Adds the given scalar to all the elements in the given matrix.

In [14]:
# Matrix-Scalar Addition

import numpy as np

x = np.matrix([[1, 2], [4, 3]])
s_sum = x + 1
print(s_sum)

[[2 3]
 [5 4]]


## Matrix Scalar Multiplication

Multiplies the given scalar to all the elements in the given matrix.

In [15]:
# Matrix Scalar Multiplication

import numpy as np

x = np.matrix([[1, 2], [4, 3]])
s_mul = x * 3
print(s_mul)

[[ 3  6]
 [12  9]]


## Matrix Multiplication

A of shape (m x n) and B of shape (n x p) multiplied gives C of shape (m x p)

In [16]:
# Matrix Multiplication

import numpy as np

a = [[1, 0], [0, 1]]
b = [1, 2]
np.matmul(a, b)

array([1, 2])

In [17]:
complex_mul = np.matmul([2j, 3j], [2j, 3j])
print(complex_mul)

(-13+0j)


## Matrix Transpose

With transposition you can convert a row vector to a column vector and vice versa:<br>
A=[aij]mxn<br>
AT=[aji]n×m<br>

In [19]:
# Matrix Transpose

import numpy as np

a = np.array([[1, 2], [3, 4]])
print(a)


[[1 2]
 [3 4]]


In [22]:
print(a.transpose())

[[1 3]
 [2 4]]


## Tensors

The more general entity of a tensor encapsulates the scalar, vector and the matrix. It is sometimes necessary — both in the physical sciences and machine learning — to make use of tensors with order that exceeds two.

In [23]:
import torch

a = torch.Tensor([26])

print(a)
print(type(a))

tensor([26.])
<class 'torch.Tensor'>


In [24]:
print(a.shape)

torch.Size([1])


In [25]:
# Creates a Random Torch Variable of size 5x3.
t = torch.Tensor(5, 3)

In [26]:
print(t)

tensor([[9.2755e-39, 1.0561e-38, 8.9082e-39],
        [9.5510e-39, 1.0469e-38, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])


In [28]:
print(t.shape)

torch.Size([5, 3])


## Few Arithmetic Operations on Tensors in Python


In [29]:
import torch

# Creating Tensors

p = torch.Tensor(4,4)
q = torch.Tensor(4,4)
ones = torch.ones(4,4)

print(p, q, ones)

tensor([[9.2755e-39, 1.0561e-38, 8.9082e-39, 9.5510e-39],
        [1.0469e-38, 4.2246e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39, 8.9082e-39]]) tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38, 9.6429e-39]]) tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [30]:
print("Addition:{}".format(p + q))
print("Subtraction:{}".format(p - ones))
print("Multiplication:{}".format(p * ones))
print("Division:{}".format(q / ones))

Addition:tensor([[1.9469e-38, 1.9010e-38, 1.9378e-38, 1.8918e-38],
        [2.0388e-38, 1.2949e-38, 1.9561e-38, 1.9561e-38],
        [2.0112e-38, 1.6898e-38, 2.0112e-38, 2.0020e-38],
        [2.0388e-38, 1.2949e-38, 1.9653e-38, 1.8551e-38]])
Subtraction:tensor([[-1., -1., -1., -1.],
        [-1., -1., -1., -1.],
        [-1., -1., -1., -1.],
        [-1., -1., -1., -1.]])
Multiplication:tensor([[9.2755e-39, 1.0561e-38, 8.9082e-39, 9.5510e-39],
        [1.0469e-38, 4.2246e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39, 8.9082e-39]])
Division:tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38, 9.6429e-39]])
