In [106]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [107]:
# Create a custom dataset

In [108]:
class WineDataset(Dataset):
    """
    we have to implement three things
    def __init__()
    def __getitem__() used for indexing
    def __len()__  to call the len(datasaet)
    """
    def __init__(self):
        # data loading
        xy = np.loadtxt('./data/wine.csv', delimiter= ',', dtype = np.float32
                       , skiprows = 1)
        self.x = torch.from_numpy(xy[:, 1:])
        self.y = torch.from_numpy(xy[:, [0]]) # n_samples, 1
        self.n_samples = xy.shape[0]
        
    def __getitem__(self, index):
        return self.x[index], self.y[index]
    
    def __len__(self):
        return self.n_samples

In [58]:
# Loading the Dataset

In [59]:
dataset = WineDataset()

In [60]:
# first_data = dataset[0]
# features, labels = first_data

In [61]:
# print(features, labels)

In [62]:
# Creating the Dataloader

In [63]:
dataloader = DataLoader(dataset = dataset, batch_size = 4, shuffle = True, 
                       num_workers = 0)
dataiter = iter(dataloader)
data = dataiter.next()
features, labels = data

In [64]:
print(features, labels)

tensor([[1.2530e+01, 5.5100e+00, 2.6400e+00, 2.5000e+01, 9.6000e+01, 1.7900e+00,
         6.0000e-01, 6.3000e-01, 1.1000e+00, 5.0000e+00, 8.2000e-01, 1.6900e+00,
         5.1500e+02],
        [1.2070e+01, 2.1600e+00, 2.1700e+00, 2.1000e+01, 8.5000e+01, 2.6000e+00,
         2.6500e+00, 3.7000e-01, 1.3500e+00, 2.7600e+00, 8.6000e-01, 3.2800e+00,
         3.7800e+02],
        [1.1760e+01, 2.6800e+00, 2.9200e+00, 2.0000e+01, 1.0300e+02, 1.7500e+00,
         2.0300e+00, 6.0000e-01, 1.0500e+00, 3.8000e+00, 1.2300e+00, 2.5000e+00,
         6.0700e+02],
        [1.3840e+01, 4.1200e+00, 2.3800e+00, 1.9500e+01, 8.9000e+01, 1.8000e+00,
         8.3000e-01, 4.8000e-01, 1.5600e+00, 9.0100e+00, 5.7000e-01, 1.6400e+00,
         4.8000e+02]]) tensor([[3.],
        [2.],
        [2.],
        [3.]])


As there are 4 batches specified, we can see 4 different feature vectos, with one instance because of **next()** method on iter

In [65]:
# Training Loop

In [68]:
# Hyper parameters
num_epochs =2 
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4) # total 
print(total_samples, n_iterations)

178 45


In [70]:
for epoch in range(num_epochs):
    for i, (inputs, labels) in enumerate(dataloader):
        
        # here: 178 samples, batch_size = 4, n_iters=178/4=44.5 -> 45 iterations
        # Run your training process
        if (i+1) % 5 == 0:
            print(f'Epoch: {epoch+1}/{num_epochs}, Step {i+1}/{n_iterations}| Inputs {inputs.shape} | Labels {labels.shape}')

Epoch: 1/2, Step 5/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch: 1/2, Step 10/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch: 1/2, Step 15/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch: 1/2, Step 20/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch: 1/2, Step 25/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch: 1/2, Step 30/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch: 1/2, Step 35/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch: 1/2, Step 40/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch: 1/2, Step 45/45| Inputs torch.Size([2, 13]) | Labels torch.Size([2, 1])
Epoch: 2/2, Step 5/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch: 2/2, Step 10/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch: 2/2, Step 15/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch: 2/2, Step 20/45| Inputs torch.Size([4, 13]) | L

In [109]:
# Data Transforms

In [110]:
class WineDataset(Dataset):
    """
    we have to implement three things
    def __init__()
    def __getitem__() used for indexing
    def __len()__  to call the len(datasaet)
    """
    def __init__(self, transform = None):
        # data loading
        xy = np.loadtxt('./data/wine.csv', delimiter= ',', dtype = np.float32
                       , skiprows = 1)
        self.x = torch.from_numpy(xy[:, 1:])
        self.y = torch.from_numpy(xy[:, [0]]) # n_samples, 1
        self.n_samples = xy.shape[0]
        self.transform = transform
        
    def __getitem__(self, index):
        return self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return self 
    
    def __len__(self):
        return self.n_samples

In [111]:
class ToTensor:
    def __call__(self, sample):
        inputs, targets = sample
        return torch.to_numpy(inputs), torch.to_numpy(targets) 

In [112]:
dataset = WineDataset(transform = ToTensor())
first_data = dataset[0]
features, labels = first_data

In [113]:
print(type(features), type(labels))

<class 'torch.Tensor'> <class 'torch.Tensor'>


In [114]:
print(features, labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [115]:
# Custom Transform

In [116]:
class MulTransform:
    # multiply inputs with a given factor
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, sample):
        inputs, targets = sample
        inputs *= self.factor
        return inputs, targets

In [117]:
print('\nWith Tensor and Multiplication Transform')
composed = torchvision.transforms.Compose([ToTensor(), MulTransform(4)])
dataset = WineDataset(transform=composed)
first_data = dataset[0]
features, labels = first_data
print(type(features), type(labels))
print(features, labels)


With Tensor and Multiplication Transform
<class 'torch.Tensor'> <class 'torch.Tensor'>
tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [118]:
composed = torchvision.transforms.Compose([ToTensor(), MulTransform(5)])
dataset = WineDataset(transform = composed)

In [119]:
first_data = dataset[0]
features, labels = first_data

In [120]:
print(features, labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])
