In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [4]:
#empty tensor
x = torch.empty(1)
print(x)
# one value means a scalar 

tensor([-6.1443e-24])


In [5]:
x = torch.empty(3) # vector, 1D
print(x)

tensor([-3.7392e-28,  5.5211e-43, -6.2620e-24])


In [6]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[2.0991e-07, 2.6728e+23, 6.4099e-10],
        [5.2594e+22, 6.7445e-10, 5.4651e-05]])


In [8]:
x = torch.empty(2,2,3) # tensor, 3 dimensions 
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [9]:
x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])


In [10]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)


tensor([[0.0823, 0.3762, 0.6396],
        [0.2132, 0.3249, 0.6538],
        [0.1212, 0.1995, 0.7836],
        [0.2945, 0.2785, 0.4342],
        [0.3950, 0.6099, 0.0262]])


In [15]:
x = torch.ones(2,2, dtype = torch.double)
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


## Operations

In [17]:
y = torch.rand(2, 2)
x = torch.rand(2, 2)

In [19]:
# elementwise addition
z = x + y
# torch.add(x,y)
print(z)
z1 = x + y
print(z1)

tensor([[1.2207, 0.9813],
        [0.8131, 0.1019]])
tensor([[1.2207, 0.9813],
        [0.8131, 0.1019]])


In [20]:
# in place addition, everything with a trailing underscore is an inplace operation
# i.e. it will modify the variable
y.add_(x)
print(y)

tensor([[1.2207, 0.9813],
        [0.8131, 0.1019]])


**Everything with a trailing underscore is an inplace operation**

In [21]:
# substraction
z = x - y
z = torch.sub(x, y)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

## Slicing

In [22]:
x = torch.rand(5,3)
print(x)

tensor([[0.3638, 0.4767, 0.8348],
        [0.6294, 0.1843, 0.4614],
        [0.9208, 0.4205, 0.7325],
        [0.3065, 0.9552, 0.3796],
        [0.2109, 0.6916, 0.1980]])


In [23]:
print(x[:, 0]) # all rows, column 0

tensor([0.3638, 0.6294, 0.9208, 0.3065, 0.2109])


In [24]:
print(x[1, :]) # row 1, all columns

tensor([0.6294, 0.1843, 0.4614])


In [26]:
print(x[1,1]) # element at 1, 1

tensor(0.1843)


In [27]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.18434971570968628


In [28]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**If -1 it pytorch will automatically determine the necessary size**

In [29]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()

In [30]:
z

tensor([[ 0.9731,  0.6646,  1.7812,  1.9467],
        [ 1.5056,  1.1333,  1.1146,  1.0780],
        [ 1.8673,  1.1403,  0.4967,  0.5985],
        [ 1.1199,  0.5322, -0.7881,  2.1545]], device='cuda:0')